Make encoder stricter
mathiasbynens/q-encoding pull request #1
Opened 2016-11-09 22:44 UTC by ConradIrwin

We use the q-encoding library to escape complex names in the To:
fields of emails, and we were tripped up by an example like this:

```
To: =?UTF-8?Q?cc:_A_Better_World?=
```

While many mime parsers seem to accept this happily, the Gmail HTTP API
which we use to send emails rejects it as invalid.

This is fixable by escaping the colon to:

```
To: =?UTF-8?Q?cc=3A_A_Better_World?=
```

Upon closer inspection of RFC2047, the list of valid characters in q-encoding
is context dependent (don't you love email standards...) so patching this
library to be as cautious as possible.

c.f. https://tools.ietf.org/html/rfc2047#section-5

2016-11-10 12:56 UTC, mathiasbynens commented
Thanks for the patch! I’m open to accepting this change.

`q.js` is generated from `src/q.js`, though, and should not be directly edited.

Could you tweak the script that generates the regular expression instead? https://github.com/mathiasbynens/q-encoding/blob/master/scripts/export-data.js Just a simple `.add(':')` should do the trick.

2016-11-10 23:33 UTC, ConradIrwin commented
Thanks @mathiasbynens, I didn't spot the build system first time through (`npm test` just uses the pre-cached version of `q.js`).

I've updated the patch to fix the source correctly, but have continued to use the strict definition of what is valid in a header. Testing using the `golang` parser (which is relatively strict) it seems that many other characters cause it problems (`,` and `"` being the obvious candidates).

If you'd rather preserve the original behaviour for q-encoding large quantities of text, I would also be open to adding a second encode method: `q.encodeHeader` that uses the stricter definition instead. (But given that there's no harm done by encoding unnecessary characters, it seems clearer to just have one `.encode` API that works everywhere).

2016-11-11 09:03 UTC, mathiasbynens commented on scripts/export-data.js
> +	.add(' ');
Space should continue to be excluded, as it’s already handled here: https://github.com/mathiasbynens/q-encoding/pull/1/files#diff-a148bc52a39c990d02038097d8177455R56

2016-11-11 09:03 UTC, mathiasbynens commented on scripts/export-data.js
> +	.addRange(65, 90)  // upper case ASCII
Let’s use `.addRange('A', 'Z')` as it’s clearer

2016-11-11 09:03 UTC, mathiasbynens commented on scripts/export-data.js
> +	.addRange(97, 122) // lower case ASCII
`.addRange('a', 'z')`

2016-11-11 09:04 UTC, mathiasbynens commented on scripts/export-data.js
> +	.addRange(48, 57)  // decimal digits
`.addRange('0', '9')`

2016-11-11 09:07 UTC, mathiasbynens requested changes
Left some more comments. Could you address those + update the two failing tests? https://travis-ci.org/mathiasbynens/q-encoding/jobs/174934322#L6042 Thanks!

2016-11-11 21:11 UTC, ConradIrwin commented
Thanks for the review @mathiasbynens, the tests are now passing, and the code is much clearer :). (regenerate is really quite powerful, thanks for that! I can see myself using it in other places too)

2016-11-14 12:20 UTC, mathiasbynens approved these changes

2016-11-14 12:22 UTC, closed without merging

2016-11-14 12:25 UTC, mathiasbynens commented
Released as v1.0.0. Thanks!